### ISSUE TITLE
Update readme re:licensing

### ISSUE THREAD

**Issue by cosmin-marginean** [vt-middleware/passay#122]
I tried inquiring about licensing to passay@googlegroups.com, as per Readme, but I've received an automatic response
```
We're writing to let you know that the group you tried to contact (passay) may not exist, or you may not have permission to post messages to the group
```

In any case, we're interested in using Passay in our closed-source (proprietary) project as a binary, but I wasn't able to tell if this possible with the current licensing structure. Would you be able to confirm the impact of the dual licensing when using Passay as a binary (.jar) dependency only?

**Comment by dfish3r** [comment]
I've had a lot of trouble with those google groups since the upgrade, posting here is fine.

The dual licensing just allows you to pick the one which best serves your needs. i.e. you can't use both licenses.
AFAIK (and it's one of the reasons we choose them) both LGPL and Apache2 can be used by closed source, proprietary software. So it's just a matter of which one you prefer.

**Comment by cosmin-marginean** [comment]
That's great, thank you so much!
