### ISSUE TITLE
IllegalArgumentException when size of characterRules is zero

### ISSUE THREAD

**Issue by hitesh22b** [vt-middleware/passay#75]
generatePassword in PasswordGenerator.java method gives IllegalArgumentExeption when the size of the list is zero. Here is the stacktrace 

java.lang.IllegalArgumentException: bound must be positive

	at java.util.Random.nextInt(Random.java:388)
	at org.passay.PasswordGenerator.fillRandomCharacters(PasswordGenerator.java:98)
	at org.passay.PasswordGenerator.generatePassword(PasswordGenerator.java:80)

In my application, the addition of rules is based on user input. If user wants Mixedcase then simply create a rule of mixedCase and add it to the list. But the minimum length rule is always there. That is user cannot disable it. So the above code is scenario when there are no rules added to list of characterRules. Ideally it should generate a password with length specified in 1 parameter even if 2nd parameter is an empty list.

Sorry  for the bad english.

**Comment by dfish3r** [comment]
`PasswordGenerator#generatePassword` uses `CharacterRule#getValidCharacters()` and `CharacterRule#getNumberOfCharacters()` to populate the contents of the password.
If there are no character rules, what characters should the password contain?

**Comment by hitesh22b** [comment]
i maybe be wrong but here's my opinion.

"if there are no character rules,what characters should password contain?"

it should contain any characters with password size specified in 1st parameter

**Comment by dfish3r** [comment]
This is easy enough for you to implement without API changes.
Simply set your own default character rule in the case where you would otherwise have no character rules.
I'm a little reluctant to make this change, even though it would be trival.
@serac do you have any thoughts about the API providing a default set of characters for password generation?

**Comment by hitesh22b** [comment]
@dfish3r, for now, I have done exactly what you mentioned. But I thought the library should take care of it instead of me. I am quite an inexperienced developer so I may be wrong.

**Comment by serac** [comment]
My initial reaction is that sensible defaults are difficult if not impossible to draft for a library like passay that implements security policy. You could argue that the present behavior of throwing is a configuration guard against bad policy; on the other hand, I think we could justifiably change the default to be "all characters" instead of "no characters" to be more user friendly. Given that both views are valid, I'm inclined to leave it.

**Comment by dfish3r** [comment]
Ok, closing for now. If we get more feedback that this is useful we'll reopen.
